[package]

name = "game"
version = "0.1.0"
authors = [
    "York Xiang <bombless@126.com>"
]

[[bin]]
name = "game"

[dependencies]
rand = "*"
piston = "0.16.0"
piston2d-graphics = "0.12.0"
pistoncore-glutin_window = "0.20.0"
piston2d-opengl_graphics = "0.21.0"
